In [49]:
# Gauss elimination implementation with partial pivoting
 
import numpy as np
import pprint as pprint

In [50]:
# Ab combined array for the exercise
a = np.array( [[1.00, 2.00,  1.0, -1.00,  5.00],
               [3.00, 2.00, 4.00,  4.00, 16.00],
               [4.00, 4.00, 3.00,  4.00, 22.00],
               [2.00, 0.00, 1.00,  5.00, 15.00] ])

print('Original array Ab:')
pprint.pprint(a)

Original array Ab:
array([[ 1.,  2.,  1., -1.,  5.],
       [ 3.,  2.,  4.,  4., 16.],
       [ 4.,  4.,  3.,  4., 22.],
       [ 2.,  0.,  1.,  5., 15.]])


In [51]:
# calculating length of array Ab
n = len(a)

In [52]:
# gauss elimination algorithm

# initializing empty array for multiplier calculation
mp = np.zeros(shape=(4,5))

for k in range(n):
    p=k
    for i in range(k, n):
        if a[i][k] >= a[p][k]:
            p = i
    if p!=k:
        a[[p, k]] = a[[k, p]]
    
    if a[k][k] == 0:
        break

    for i in range(k+1, n):
        mp[i][k] = a[i][k]/a[k][k]
   
        for j in range(n+1):
            a[i][j] = a[i][j] - mp[i][k] * a[k][j]

    print('\n -------- Iteration #%d -------- '%(k))
    print('\nArray:')
    pprint.pprint(a)
    print('\nMultiplier array:')
    pprint.pprint(mp)


 -------- Iteration #0 -------- 

Array:
array([[ 4.  ,  4.  ,  3.  ,  4.  , 22.  ],
       [ 0.  , -1.  ,  1.75,  1.  , -0.5 ],
       [ 0.  ,  1.  ,  0.25, -2.  , -0.5 ],
       [ 0.  , -2.  , -0.5 ,  3.  ,  4.  ]])

Multiplier array:
array([[0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.  , 0.  , 0.  , 0.  ]])

 -------- Iteration #1 -------- 

Array:
array([[ 4.  ,  4.  ,  3.  ,  4.  , 22.  ],
       [ 0.  ,  1.  ,  0.25, -2.  , -0.5 ],
       [ 0.  ,  0.  ,  2.  , -1.  , -1.  ],
       [ 0.  ,  0.  ,  0.  , -1.  ,  3.  ]])

Multiplier array:
array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.75,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.25, -1.  ,  0.  ,  0.  ,  0.  ],
       [ 0.5 , -2.  ,  0.  ,  0.  ,  0.  ]])

 -------- Iteration #2 -------- 

Array:
array([[ 4.  ,  4.  ,  3.  ,  4.  , 22.  ],
       [ 0.  ,  1.  ,  0.25, -2.  , -0.5 ],
       [ 0.  ,  0.  ,  2.  , -1.  , -1.  ],
       [ 0.  ,  

In [53]:
# splitting the array a into u and b for back substitution
u = np.delete(a,n,1)
b = np.delete(a,range(n),1)

In [54]:
# back substitution algorithm

# array for x results
x=np.zeros(n)

for j in reversed(range(n)):
    if u[j][j] == 0:
        break
    
    x[j] = b[j] / u[j][j]

    for i in range(j):
        b[i] = b[i] - u[i][j]*x[j]


print('Back substitution results:')
for i in range (len(x)):
    print('x%d: %2.2f' %(i,x[i])) 

Back substitution results:
x0: 16.00
x1: -6.00
x2: -2.00
x3: -3.00
